[tool.poetry]
name = "homework_6"
version = "0.1"
description = "web-project"
authors = ["Nazar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
